all:
	g++ -g -L/home/tongpingliu/falsesharing/cheetah -o test test.cpp -lpthread -ldefault64
#	g++ -g -DUSING_IBS -L/home/tongpingliu/falsesharing/cheetah -o test test.cpp -lpthread -ldefault64

clean:
	rm -f test
